default: &default
  adapter: postgresql
  encoding: unicode
  database: kd_development
  pool: 5
  username: 
  password: 

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
