default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: kd_development

test:
  <<: *default
  database: kd_test

production:
  <<: *default
  database: kd_production
